### ISSUE TITLE
Circle is not resourced to accomplish it's goals

### ISSUE THREAD

**Issue by stephen-rowan** [Catalyst-Circle/Catalyst-Prioritized-Problems#44]
We need to work on CCv2 initial budget so the next CC can have funds to do the basic functions.

Draft proposal for CCv2 funding:
https://docs.google.com/spreadsheets/d/14SNn0WX1etdmU8zab5x4RwC5dneeEw3zD5lUb5Gimlo/edit#gid=1988897668

Awaiting results from submitted proposals.

┆Issue is synchronized with this [Trello card](https://trello.com/c/wog48X6F) by [Unito](https://www.unito.io)

**Comment by stephen-rowan** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Circle is not resourced to accomplish it's goals](https://trello.com/c/W9nsCDwH/20-circle-is-not-resourced-to-accomplish-its-goals)

**Comment by kenricnelson** [comment]
While I commend the efforts of Stephen and Nori to finance the administration of the circle through a Catalyst proposal and the operation of a stakepool, a more sustainable method based on an operational budget from the Treasury is needed.  As a first step, can IOG provide the circle with records of the budget that has been devoted to running the Circle activities?  How many IOG employees have been involved, what is the percentage of their time, what is the approximate cost of these activities?

The concern is that without a more realistic estimate of the costs to run Catalyst and a plan for community input to allocate the required resources to run the Catalyst program on a long-term basis the operation of the program will flounder.
